### ISSUE TITLE
Problem with the signal

### ISSUE THREAD

**Issue by jorgeeegj** [jmrplens/PyOctaveBand#1]
Hi, 
I have tried the function octavefilter with my signals, which are in a big dataframe, and gives me an error "tuple index out of range" in the command: sd = signal.decimate(x, factor[idx]). The signal has a length of 32768x1. So I also proved the traspose but I have the same error.
I have proved the usage example and it works perfect and it´s length is 240000. I observe that the type of the signal is an ndarray so I try to convert my column of my dataframe to an ndarray but didn´t let me.

Besides I prove with the audio in type memmap but doesn´t works, the same error as with the dataframe, and don´t let me to convert to an ndarray.

Thank you in advance.

**Comment by jorgeeegj** [comment]
I forgot to write here when I fixed the error, the only thing I had to have was convert the column of my dataframe into a list.

This function was very useful for me.

**Comment by jmrplens** [comment]
Hi @jorgeeegj,

That's right, if I see it necessary to add an error message if the type of data entered is not correct, that will save many headaches that happens to all of us 😅
