### ISSUE TITLE
Problem in decimation

### ISSUE THREAD

**Issue by ashley-b** [jmrplens/PyOctaveBand#2]
Hi, let me start of by saying am not a DSP expert.
But I have noticed scipy.signal.decimate gives poor results with large decimation values

![signal decimate](https://user-images.githubusercontent.com/5248379/188457288-cab98499-5b1e-4bb3-9f12-d5eab68774c4.png)
But when I change
https://github.com/jmrplens/PyOctaveBand/blob/d9b36e6e99221e7443d13ab684c938acd412aa87/PyOctaveBand.py#L54
to
```
sd = signal.resample(x, (int)(len(x) / factor[idx]))
```
I see this improvement
![signal resample](https://user-images.githubusercontent.com/5248379/188457545-a873c4ce-279b-4b93-a7b5-8c90366709af.png)

I believe it is related to the note about not using decimate with values high than 13
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.decimate.html#scipy.signal.decimate

**Comment by jmrplens** [comment]
Hi @ashley-b,

You are right, I had not seen that limitation. 

Thank you very much for analyzing the results and coming up with the solution!
If you want, you can make a Pull Request or else I'll edit it directly mentioning you.

**Comment by ashley-b** [comment]
No problems, I created a PR #4
